import AppKit

/// Insertion by transient paste: one ⌘V instead of a synthetic keystroke per
/// character. The staged item is marked transient and auto-generated, the two
/// conventions clipboard managers honour to skip recording (nspasteboard.org),
/// and the previous contents go back once the paste has landed.
enum Pasteboard {
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Long enough for the receiving app to have read the pasteboard; restoring
    /// early would make it paste the restored contents instead.
    static let restoreDelay: TimeInterval = 0.35

    private static var pendingRestore: DispatchWorkItem?
    private static var saved: [[NSPasteboard.PasteboardType: Data]]?

    /// Puts `value` on the pasteboard for the caller to paste. False means the
    /// value could not be staged and the caller should type it instead.
    @discardableResult
    static func stage(_ value: String, into pasteboard: NSPasteboard = .general) -> Bool {
        guard !value.isEmpty else { return false }

        // A restore already in flight holds the user's real contents; keep it
        // rather than snapshotting our own staged item over it.
        if pendingRestore == nil { saved = capture(pasteboard) }
        pendingRestore?.cancel()

        let item = NSPasteboardItem()
        item.setString(value, forType: .string)
        item.setString("", forType: transientType)
        item.setString("", forType: autoGeneratedType)

        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else {
            saved = nil
            return false
        }

        let stagedChangeCount = pasteboard.changeCount
        let restore = DispatchWorkItem {
            defer {
                pendingRestore = nil
                saved = nil
            }
            // Something newer arrived; it outranks what we saved.
            guard pasteboard.changeCount == stagedChangeCount else { return }
            guard let saved, !saved.isEmpty else {
                pasteboard.clearContents()
                return
            }
            pasteboard.clearContents()
            pasteboard.writeObjects(saved.map(item(from:)))
        }
        pendingRestore = restore
        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay, execute: restore)
        return true
    }

    /// Promised and lazily provided types answer no data and cannot be put back.
    private static func capture(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? []).map { item in
            item.types.reduce(into: [:]) { contents, type in
                if let data = item.data(forType: type) { contents[type] = data }
            }
        }
    }

    private static func item(from contents: [NSPasteboard.PasteboardType: Data]) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        for (type, data) in contents {
            item.setData(data, forType: type)
        }
        return item
    }
}
