import AppKit

/// Insertion by transient paste: one ⌘V instead of a synthetic keystroke per
/// character. The staged item is marked transient and auto-generated, the two
/// conventions clipboard managers honour to skip recording (nspasteboard.org),
/// and the previous contents go back once the paste has landed.
///
/// The value is provided lazily, so staging also tells us when the target app
/// actually reads it. Nothing reading it means the ⌘V never landed.
enum Pasteboard {
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Never restore sooner than this, even after a read: some apps read the
    /// string more than once while handling a single paste.
    private static let minimumRestoreDelay: TimeInterval = 0.35
    private static let restoreAfterRead: TimeInterval = 0.15

    /// How long a ⌘V gets before it counts as not landed. Slow readers (remote
    /// desktops, VMs) get this long instead of a fixed 350ms.
    static let readTimeout: TimeInterval = 1.0

    private static var current: StagedPaste?
    private static var saved: [[NSPasteboard.PasteboardType: Data]]?

    /// Puts `value` on the pasteboard for the caller to paste. Nil means the
    /// value could not be staged and the caller should type it instead.
    static func stage(_ value: String, into pasteboard: NSPasteboard = .general) -> StagedPaste? {
        guard !value.isEmpty else { return nil }

        // A paste still in flight means the pasteboard holds our item, not the
        // user's; keep the snapshot taken before it.
        if current == nil { saved = capture(pasteboard) }
        current?.cancelRestore()

        let staged = StagedPaste(value: value)
        let item = NSPasteboardItem()
        item.setDataProvider(staged, forTypes: [.string])
        item.setString("", forType: transientType)
        item.setString("", forType: autoGeneratedType)

        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else {
            saved = nil
            return nil
        }
        current = staged
        staged.scheduleRestore(changeCount: pasteboard.changeCount) {
            restore(pasteboard, stagedChangeCount: $0)
        }
        return staged
    }

    private static func restore(_ pasteboard: NSPasteboard, stagedChangeCount: Int) {
        defer {
            current = nil
            saved = nil
        }
        // Something newer arrived; it outranks what we saved.
        guard pasteboard.changeCount == stagedChangeCount else { return }
        pasteboard.clearContents()
        if let saved, !saved.isEmpty {
            pasteboard.writeObjects(saved.map(item(from:)))
        }
    }

    /// Promised and lazily provided types answer no data and cannot be put back.
    private static func capture(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? []).map { item in
            item.types.reduce(into: [:]) { contents, type in
                if let data = item.data(forType: type) { contents[type] = data }
            }
        }
    }

    private static func item(from contents: [NSPasteboard.PasteboardType: Data]) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        for (type, data) in contents {
            item.setData(data, forType: type)
        }
        return item
    }

    /// One staged value. Answers the pasteboard's request for the string and
    /// remembers that it happened. AppKit may ask from any thread, so the read
    /// time sits behind a lock.
    final class StagedPaste: NSObject, NSPasteboardItemDataProvider, @unchecked Sendable {
        private let value: String
        private let stagedAt = ProcessInfo.processInfo.systemUptime
        private let lock = NSLock()
        private var firstRead: TimeInterval?
        private var restoreCheck: DispatchWorkItem?

        private var readAt: TimeInterval? { lock.withLock { firstRead } }

        init(value: String) {
            self.value = value
        }

        var wasRead: Bool { readAt != nil }

        /// Waits until the target reads the value, up to `readTimeout`.
        func waitForRead() async -> Bool {
            while !wasRead, ProcessInfo.processInfo.systemUptime - stagedAt < Pasteboard.readTimeout {
                try? await Task.sleep(for: .milliseconds(20))
            }
            return wasRead
        }

        func pasteboard(
            _ pasteboard: NSPasteboard?,
            item: NSPasteboardItem,
            provideDataForType type: NSPasteboard.PasteboardType
        ) {
            item.setString(value, forType: type)
            let now = ProcessInfo.processInfo.systemUptime
            lock.withLock { if firstRead == nil { firstRead = now } }
        }

        func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}

        fileprivate func scheduleRestore(changeCount: Int, restore: @escaping (Int) -> Void) {
            let check = DispatchWorkItem { [weak self] in
                guard let self else { return }
                let now = ProcessInfo.processInfo.systemUptime
                let due = readAt.map { max(self.stagedAt + Pasteboard.minimumRestoreDelay, $0 + Pasteboard.restoreAfterRead) }
                    ?? stagedAt + Pasteboard.readTimeout
                if now >= due {
                    restore(changeCount)
                } else {
                    scheduleRestore(changeCount: changeCount, restore: restore)
                }
            }
            restoreCheck = check
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.05, execute: check)
        }

        fileprivate func cancelRestore() {
            restoreCheck?.cancel()
        }
    }
}
